### ISSUE TITLE
Error handling in case the log file is already busy

### ISSUE THREAD

**Issue by marcbachmann** [flumedb/aligned-block-file#1]
We could expose the `fd` [instance](https://github.com/flumedb/aligned-block-file/blob/master/file.js#L12) which we can then again use in `flumelog-offset` and other logs.
That way we could handle the `fs.open` error using `fd.once(function (errOrOffset) {})`.

As I want the `flumelog-offset` module in a read-only mode, I don't need to create directories or open the file if it doesn't exist. Can we make those operations optional.

**Comment by dominictarr** [comment]
if you are reusing it within the same process, can't you just pass the log instance around?
outside of testing, I can't really think of a reason you'd want to open the same log twice in the same process.

**Comment by marcbachmann** [comment]
No, I just thought that because of that strange error handling: https://github.com/flumedb/aligned-block-file/blob/master/file.js#L13

Some callback-style error handling would be better. I'd like to instantiate many (maybe a few thousand) instances per day and therefore it needs proper error handling. I also don't need the whole overhead of creating directories. Directories already exist in my case.

**Comment by marcbachmann** [comment]
I can also wait with that until I run into an error.
I'm currently just evaluating append only logs for a product.
I'm not sure yet whether I'll use flumelog-offset. There's the disadvantage of not being able to compress the file like with raw text files.

**Comment by dominictarr** [comment]
I doubt that mkdrip adds much overhead, if you are only doing a few thousand a day, it checks if the file already exists, only creates it if necessary. I guess we could move that into a open-or-create module that tries to open, then creates the directory if it didn't work, etc.

you could write another framing strategy that was text based!

**Comment by marcbachmann** [comment]
I'm currently using protocol buffers as codec. That's quite neat for structured data. I'll know whether it's suitable for text once I fill it with production data.

**Comment by marcbachmann** [comment]
Closing this as it isn't needed at the moment.
👌... yes, I might do something after the pr with the flags.
